### ISSUE TITLE
USER STORY: In order to automatically hide the poll as an administrator, I can pick the expiry date while publishing the pol

### ISSUE THREAD

**Issue by araldwin** [araldwin/Love-running-project#4]
in  order to **{receive benefit}** as a **{role}**, I can **{goal/desire}**

## Acceptance Criteria:
-----
**a.** The poll should disappear at 11:59 PM on the target date
**b.** The real estate of the "Poll" should be reversed on the home page. a message that says "Stay tuned, a new poll is coming soon" should appear if no other Poll is active.
**c.** The Administrator expiry date should be at least 3 days after the current date.

## Tasks
------
- [x] Update the admin module view: the poll design (HTML and CSS) to include date picker
- [ ] Update the website view: show "Stay tuned, a new poll is coming soon"
- [ ] Create a Javascript function to validate the expiry date is at least after 3 days.
- [ ] Create a job to check expired Polls everyday at 11:59 PM and Hide them
- [ ] Update the controller function
- [ ] Update unit test scripts
- [ ] Test functionality
